imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

doctrine:
    dbal:
        driver: pdo_mysql
        host: 'localhost'
        port: '%database_port%'
        dbname: 'id2941199_oil'
        user: 'id2941199_oil'
        password: 'hfn031hfn'
        charset: UTF8

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
